### PR TITLE
changes on README

### PR DESCRIPTION
**Pull request by stummjr**
Hey, I made some changes to README and I would like to have your feedback on them.

**Summary of changes:**
- moved the "Scrapy+Splash" section to the end of the doc and renamed it to "Why not use the Splash HTTP API directly?". I think that this way, the doc would be more straightforward to follow.
- minor fixes on typos and rephrased some sentences.
- changed the CI image URL, because it was broken.

### CODE REVIEW

**Comment by pablohoffman** [comment]
Looks good to me.

I know it's not related to this change, but shouldn't we also rename `scrapyjs` module to `scrapy_splash` for consistency?. And maybe also move this repo to [scrapy-plugins](https://github.com/scrapy-plugins) github account, aimed to be used as directory of official Scrapy extensions.

**Comment by stummjr** [comment]
@pablohoffman: :+1: 
There is also the package on PyPI, which is called [`scrapyjs`](https://pypi.python.org/pypi/scrapyjs/).

**Comment by stummjr** [comment]
Hey! Is there anything else I should change in the readme?

**Comment by redapple** [comment]
@stummjr , thanks for this.
Let's merge this one, @kmike what do you think?
And handle the renaming/moving to scrapy-plugins as seperate issue.

**Comment by kmike** [comment]
Thanks @stummjr! Rebased & merged.

**Pull request closed without merging**
