### PR TITLE
remove calls to to_native_str -> to_unicode

### LINKED ISSUE #253: Got warning; ScrapyDeprecationWarning: Call to deprecated function to_native_str. Use to_unicode instead.
Hi, i got this warning after I ran the spider.

[py.warnings] WARNING: /usr/local/lib/python3.7/dist-packages/scrapy_splash/request.py:41: ScrapyDeprecationWarning: Call to deprecated function to_native_str. Use to_unicode instead.
  url = to_native_str(url)

I use Scrapy 2.0

### PR DESCRIPTION
**Pull request by Rafiot**
Fix #253

### CODE REVIEW

**Comment by Rafiot** [comment]
The test suite didn't run for a very long time, this PR will also fix that.

**Comment by Rafiot** [comment]
Well, maybe. The test suite is incompatible with scrapy >= 1.8, and I'm not totally sure why.

**Comment by Rafiot** [comment]
Okay, so at this point, what still fails is when the URL passed to requests is `None`, and it then fallback to `about:blank`, which is considered invalid by scrapy >= 2.

**Comment by Rafiot** [comment]
... it fails on scrapy 1.0.7.

Do you really still want to support that?

**Comment by Rafiot** [comment]
The last commit remove the support for scrapy < 1.1.0. Feel free to revert that if you don't like it.

**Review by lopuhin — COMMENTED** [review]
Thanks for the PR @Rafiot and taking care of the build issues. Indeed it's fine to drop support for scrapy < 1.1. The changes look great 👍 

It seems that scrapy 2.3 is still failing the build (under py35+) due to ``about:blank`` URL being invalid. This was probably broken by this change https://github.com/scrapy/scrapy/pull/4094 - not sure yet what to best do here. As a work-around for this PR, we could limit scrapy version used in tests, and tackle this in a separate issue.

**Comment by Rafiot** [comment]
Thank you :) 

Yeah, travis with python 3.4 is using scrapy 1.7.x (because scrapy 1.8 requires python 3.5+). 

If I understand the code right, `SplashRequest` shouldn't fallback to `about:blank` anymore (https://github.com/scrapy-plugins/scrapy-splash/blob/master/scrapy_splash/request.py#L40), require an `url` parameter, and the test cases doing the calls without an `url` should be removed.

**Comment by lopuhin** [comment]
> If I understand the code right, SplashRequest shouldn't fallback to about:blank anymore, require an url parameter

Good point - yes it looks like a better long-term solution. I checked the README and we never advertise that ``url`` is optional, so while it's backwards incompatible, it looks fine to change (we'll mention it in the release notes) - and this optional ``url`` does not work any more with recent scrapy anyways.

> and the test cases doing the calls without an url should be removed

``test_splash_request_no_url`` can be removed, but at least some tests in ``tests/test_fingerprints.py`` still test useful things unrelated to an empty url it seems, so I think it's best to add some url here https://github.com/scrapy-plugins/scrapy-splash/blob/e40ca4f3b367ab463273bee1357d3edfe0601f0d/tests/test_fingerprints.py#L111-L113

**Comment by Rafiot** [comment]
:+1: I have the branch in front of me, let me do that. And I found a few try/except that are there to support scrapy < 1, I'll remove them too.

**Review by lopuhin — APPROVED** [review]
Looks great, thanks @Rafiot ! Leaving PR open for a bit in case someone else wants to review.

**Comment by Rafiot** [comment]
Sounds good, I hope it will make it into the next release :) 

And if at some point you want one to remove python 2.7 support, let me know.

**Comment by lopuhin** [comment]
Thanks again @Rafiot .

@Gallaecio @kmike I think we can make 0.8.0 now, is there anything else we want to include?

**Comment by lopuhin** [comment]
@Rafiot we'd like to include a bit more things into the next release, in should happen in a few weeks. In the meantime, it would be possible to install the package from github directly.

**Comment by Rafiot** [comment]
sounds good, thank you!

**Comment by MaytzgeM** [comment]
Hi guys, I was wondering if you could make that stable version available now. Would be greatly appreciated.

**Pull request merged**
