### PR TITLE
Add Python 3 compatibility + Python 3 Travis-CI tests

### PR DESCRIPTION
**Pull request by redapple**
Continuation of #33

### CODE REVIEW

**Comment by redapple** [comment]
@kmike , @holgerd77 , 
how does it look?

**Comment by holgerd77** [comment]
Is it intended to not include the `Six` dependency in the `requirements-py3.txt` but in the `setup.py` file?

**Comment by redapple** [comment]
not intended @holgerd77 . will add it.

**Comment by holgerd77** [comment]
Any idea when this will be merged?

**Comment by kmike** [comment]
@redapple @holgerd77 sorry for a delay!

**Comment by holgerd77** [comment]
Cool! :-)

**Pull request merged**
