### PR TITLE
Crawlera integration and splash exit proxy support

### PR DESCRIPTION
**Pull request by dvdbng**
Needs splash 1.7 in the server or greater in the server for Crawlera integration and the next release of splash (with this PR  https://github.com/scrapinghub/splash/pull/280) to set the splash exit proxy to something other than Crawlera (Issue #23)

### CODE REVIEW

**Comment by kmike** [comment]
Hey @Youwotma,

I think Crawlera integration is not an good feature for scrapy-splash; we should think of a way to make scrapy-splash more extensible without adding Crawlera integration directly.

**Comment by dvdbng** [comment]
So a different middleware? I thought having "scrapy-splash-crawlera" would not be preferable.

**Comment by Skyross** [comment]
Really need this feature. Any news about it?

**Comment by dvdbng** [comment]
Hi @Skyross, you can grab the lua script from this pull request and use it in your spider, send scrapy request with the appropriate meta parameters:

```
request.meta = {
        "splash": {
            "endpoint": "execute",
            "args": {
                 "lua_source": <read the lua script and pass here>,
                 "crawlera": {"user": "...", "pass": "..."}
             }
        } 
```

**Comment by Skyross** [comment]
@Youwotma Thank you! Will use it next time.

**Pull request closed without merging**
