### PR TITLE
Fix github action badge

### PR DESCRIPTION
**Pull request by Laerte**
Fix github action badge link

### CODE REVIEW

**Comment by Gallaecio** [comment]
@elacuesta I copied the badge URL from https://github.com/scrapy/itemadapter, where it is working. But I did indeed forgot to check that it worked here, and I have no idea why it works there.

Does the itemadapter badge does what I think and covers all workflows in a single badge? If so, how to do the same here?

**Comment by elacuesta** [comment]
~Well, to be honest, I don't really know either 😅~ (see the comment below)
It might be time to change the badge for `itemadapter` too.

**Comment by elacuesta** [comment]
It seems to me like workflow names are accepted (for itemadapter those would be "Checks", "Publish", "Tests"). We had them all consolidated under "Build" some time ago, so I think the reason it works is because it's an old badge, it's really not a valid badge for the current status.

**Comment by Laerte** [comment]
@elacuesta You are right, this is the commit that "Build" are deprecated. https://github.com/scrapy/itemadapter/commit/2735ff3feaa27b8d9c2aa49d26536f60c866c244#diff-87ee5504a3e25ac558b343724c905f2f7949e8cec3d92b9c4300bb922afa164f

@Gallaecio Should i change and just leave "Tests" badge?

**Comment by Gallaecio** [comment]
> @Gallaecio Should i change and just leave "Tests" badge?

I think so. I mean, if the Publish job ever fails, that’s something we would fix within minutes.

**Comment by Laerte** [comment]
@Gallaecio Done.

**Review by Gallaecio — APPROVED** [review]

**Comment by Laerte** [comment]
@elacuesta Can we merge this one too?

**Pull request merged**
