### PR TITLE
allow to use splash servers with basic authentication access

### PR DESCRIPTION
**Pull request by kalessin**

### CODE REVIEW

**Comment by pablohoffman** [comment]
isn't  `SPLASH_USER` & `SPLASH_PASS` more consistent with other components (like crawlera middleware)?

**Comment by kalessin** [comment]
ok, will change that

**Comment by kalessin** [comment]
That is because mesos splash instances are apikey authenticated and in that case I usually think in terms of "apikey:" strings :P

**Comment by pablohoffman** [comment]
fair point

**Comment by kalessin** [comment]
PR updated

**Comment by kmike** [comment]
Hi @kalessin,

This feature is a bit odd because Splash doesn't have auth built-in. Maybe we should add built-in Basic Auth support to Splash.

The problem with scrapyjs is that it doesn't allow to set custom HTTP headers sent to Splash. If we fix it (e.g. by adding a parameter with custom headers) then one will be able to create a wrapper function which sets up the auth. This way we won't have to explain that we have SPLASH_USER and SPLASH_PASS options in scrapyjs, but no auth support in Splash itself, and the feature won't be limited to HTTP Basic Auth, 1 set of credentials.  

Also, the PR needs tests and docs to be merged :)

**Comment by kalessin** [comment]
@kmike splash not, but splash servers deployed via mesos yes, and we do use such a service. That does not need to be handled by splash directly.

**Comment by chekunkov** [comment]
+0 

Why not to keep this inside project? I'm not strictly agains this change, but I agree with @kmike that it's strange to support auth while we don't have auth implementation in Splash. The fact we have basic auth for Splash instances in mesos is just our specifics, that's not related to Splash or scrapyjs functionality in general. I think scrapyjs code should have strict area of responsibility - it should cover features of Splash and make interaction between Scrapy and Splash easy. Handling auth is beyond this responsibility.

**Comment by kalessin** [comment]
scrapyjs is a middleware, I don't see why should be tied to what splash server can do or not and why mware must assume that the target splash server cannot be wrapped.

**Comment by dangra** [comment]
+1 running splash behind a reverse proxy is a common case and the only way to limit access to Splash in any production environment using Splash. I don't see what is the point of limiting the middleware for such basic use case.

**Comment by chekunkov** [comment]
My opinion is based on the fact that Splash doesn't implement any authentication. If reverse proxy is used to limit access to resource - don't you think it's better to have downloader middleware which would implement basic auth? E.g. it's possible to have multiple services behind the same reverse proxy, auth downloader middleware could cover all such services at once.

**Comment by pablohoffman** [comment]
+1 to merge when tests & doc are added.

@chekunkov point is a valid one, but a whole separate content for this tiny bit of functionality is too much overhead for me. I don't think `scrapyjs` needs to maintain that much feature-parity with splash server.

**Comment by redapple** [comment]
@kalessin , any update on tests and docs?

**Comment by pablohoffman** [comment]
@kalessin any chance you could add doc/tests soon and get this over with?

**Comment by kmike** [comment]
I'm closing this issue because it is possible to use HttpAuthMiddleware to access Splash protected by HTTP Basic Auth (just checked that). 

If HttpAuthMiddleware is not flexible enough for all use cases then we should fix it in Scrapy.

**Pull request closed without merging**
